### ISSUE TITLE
Bug: Failed to render the buttons after Obsidian updating to v0.15.6

### ISSUE THREAD

**Issue by hustrjh** [shabegom/buttons#124] opened 2022-07-14 02:57 UTC
## Bug
I just updated Obsidian from v0.14.15 to v0.15.6. Then some plugins including **`buttons`** can't work normally. I can't see any buttons in `reading mode` and even use them.

**Comment by Vyeche** [comment] 2022-09-02 13:21
If I click the open code and click away the button shows up. When I navigate away, the button breaks.

**Comment by shabegom** [comment] 2022-09-02 14:10
duplicate of #125

**Closed by shabegom** 2022-09-02 14:10 UTC
Labels: bug
